//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.261
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// このソース コードは xsd によって自動生成されました。Version=4.0.30319.1 です。
// 
namespace XmlSetting {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://toro.2ch.net/test/read.cgi/win/1330826421/sm4win8.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://toro.2ch.net/test/read.cgi/win/1330826421/sm4win8.xsd", IsNullable=false)]
    public partial class startmenuSetting {
        
        private startmenuSettingSetting settingField;
        
        private startmenuSettingPower powerField;
        
        private startmenuSettingItems itemsField;
        
        private startmenuSettingPrograms programsField;
        
        private startmenuSettingIcon iconField;
        
        /// <remarks/>
        public startmenuSettingSetting setting {
            get {
                return this.settingField;
            }
            set {
                this.settingField = value;
            }
        }
        
        /// <remarks/>
        public startmenuSettingPower power {
            get {
                return this.powerField;
            }
            set {
                this.powerField = value;
            }
        }
        
        /// <remarks/>
        public startmenuSettingItems items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        public startmenuSettingPrograms programs {
            get {
                return this.programsField;
            }
            set {
                this.programsField = value;
            }
        }
        
        /// <remarks/>
        public startmenuSettingIcon icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://toro.2ch.net/test/read.cgi/win/1330826421/sm4win8.xsd")]
    public partial class startmenuSettingSetting {
        
        private string taskbarHeightField;
        
        private windowDesign windowDesignField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string taskbarHeight {
            get {
                return this.taskbarHeightField;
            }
            set {
                this.taskbarHeightField = value;
            }
        }
        
        /// <remarks/>
        public windowDesign windowDesign {
            get {
                return this.windowDesignField;
            }
            set {
                this.windowDesignField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://toro.2ch.net/test/read.cgi/win/1330826421/sm4win8.xsd")]
    public enum windowDesign {
        
        /// <remarks/>
        transparent,
        
        /// <remarks/>
        normal,
        
        /// <remarks/>
        glass,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://toro.2ch.net/test/read.cgi/win/1330826421/sm4win8.xsd")]
    public partial class menuFile {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        private string headField;
        
        private bool visibleField;
        
        private bool actAsShortcutField;
        
        public menuFile() {
            this.visibleField = true;
            this.actAsShortcutField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("directory", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("knownFolder", typeof(menuFileKnownFolder))]
        [System.Xml.Serialization.XmlElementAttribute("shellLibrary", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("shellSearchCollection", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string head {
            get {
                return this.headField;
            }
            set {
                this.headField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool actAsShortcut {
            get {
                return this.actAsShortcutField;
            }
            set {
                this.actAsShortcutField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://toro.2ch.net/test/read.cgi/win/1330826421/sm4win8.xsd")]
    public partial class menuFileKnownFolder {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("canonicalName", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("folderId", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("parsingName", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("path", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://toro.2ch.net/test/read.cgi/win/1330826421/sm4win8.xsd", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        canonicalName,
        
        /// <remarks/>
        folderId,
        
        /// <remarks/>
        parsingName,
        
        /// <remarks/>
        path,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://toro.2ch.net/test/read.cgi/win/1330826421/sm4win8.xsd", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        directory,
        
        /// <remarks/>
        knownFolder,
        
        /// <remarks/>
        shellLibrary,
        
        /// <remarks/>
        shellSearchCollection,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://toro.2ch.net/test/read.cgi/win/1330826421/sm4win8.xsd")]
    public partial class menuItem {
        
        private execute executeField;
        
        private string headField;
        
        private bool visibleField;
        
        public menuItem() {
            this.visibleField = true;
        }
        
        /// <remarks/>
        public execute execute {
            get {
                return this.executeField;
            }
            set {
                this.executeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string head {
            get {
                return this.headField;
            }
            set {
                this.headField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://toro.2ch.net/test/read.cgi/win/1330826421/sm4win8.xsd")]
    public partial class execute {
        
        private commandType commandTypeField;
        
        private string commandField;
        
        private string parameterField;
        
        private windowState windowStateField;
        
        public execute() {
            this.windowStateField = windowState.normal;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public commandType commandType {
            get {
                return this.commandTypeField;
            }
            set {
                this.commandTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string command {
            get {
                return this.commandField;
            }
            set {
                this.commandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(windowState.normal)]
        public windowState windowState {
            get {
                return this.windowStateField;
            }
            set {
                this.windowStateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://toro.2ch.net/test/read.cgi/win/1330826421/sm4win8.xsd")]
    public enum commandType {
        
        /// <remarks/>
        command,
        
        /// <remarks/>
        open,
        
        /// <remarks/>
        builtIn,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://toro.2ch.net/test/read.cgi/win/1330826421/sm4win8.xsd")]
    public enum windowState {
        
        /// <remarks/>
        normal,
        
        /// <remarks/>
        close,
        
        /// <remarks/>
        minimized,
        
        /// <remarks/>
        maximized,
        
        /// <remarks/>
        hidden,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://toro.2ch.net/test/read.cgi/win/1330826421/sm4win8.xsd")]
    public partial class startmenuSettingPower {
        
        private object[] powerButtonField;
        
        private startmenuSettingPowerPowerMenu powerMenuField;
        
        private bool visibleField;
        
        public startmenuSettingPower() {
            this.visibleField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("menuFile", typeof(menuFile), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("menuItem", typeof(menuItem), IsNullable=false)]
        public object[] powerButton {
            get {
                return this.powerButtonField;
            }
            set {
                this.powerButtonField = value;
            }
        }
        
        /// <remarks/>
        public startmenuSettingPowerPowerMenu powerMenu {
            get {
                return this.powerMenuField;
            }
            set {
                this.powerMenuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://toro.2ch.net/test/read.cgi/win/1330826421/sm4win8.xsd")]
    public partial class startmenuSettingPowerPowerMenu {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("menu", typeof(menu))]
        [System.Xml.Serialization.XmlElementAttribute("menuFile", typeof(menuFile))]
        [System.Xml.Serialization.XmlElementAttribute("menuItem", typeof(menuItem))]
        [System.Xml.Serialization.XmlElementAttribute("recent", typeof(recent))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://toro.2ch.net/test/read.cgi/win/1330826421/sm4win8.xsd")]
    public partial class menu {
        
        private object[] itemsField;
        
        private string headField;
        
        private bool visibleField;
        
        public menu() {
            this.visibleField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("menu", typeof(menu))]
        [System.Xml.Serialization.XmlElementAttribute("menuFile", typeof(menuFile))]
        [System.Xml.Serialization.XmlElementAttribute("menuItem", typeof(menuItem))]
        [System.Xml.Serialization.XmlElementAttribute("recent", typeof(recent))]
        [System.Xml.Serialization.XmlElementAttribute("separater", typeof(separater))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string head {
            get {
                return this.headField;
            }
            set {
                this.headField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://toro.2ch.net/test/read.cgi/win/1330826421/sm4win8.xsd")]
    public partial class recent {
        
        private recentType typeField;
        
        private bool typeFieldSpecified;
        
        private string countField;
        
        private bool actAsMenuField;
        
        private bool visibleField;
        
        public recent() {
            this.countField = "1";
            this.actAsMenuField = false;
            this.visibleField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public recentType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        [System.ComponentModel.DefaultValueAttribute("1")]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool actAsMenu {
            get {
                return this.actAsMenuField;
            }
            set {
                this.actAsMenuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://toro.2ch.net/test/read.cgi/win/1330826421/sm4win8.xsd")]
    public enum recentType {
        
        /// <remarks/>
        program,
        
        /// <remarks/>
        file,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://toro.2ch.net/test/read.cgi/win/1330826421/sm4win8.xsd")]
    public partial class separater {
        
        private bool visibleField;
        
        public separater() {
            this.visibleField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://toro.2ch.net/test/read.cgi/win/1330826421/sm4win8.xsd")]
    public partial class startmenuSettingItems {
        
        private menu menuField;
        
        /// <remarks/>
        public menu menu {
            get {
                return this.menuField;
            }
            set {
                this.menuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://toro.2ch.net/test/read.cgi/win/1330826421/sm4win8.xsd")]
    public partial class startmenuSettingPrograms {
        
        private menu menuField;
        
        /// <remarks/>
        public menu menu {
            get {
                return this.menuField;
            }
            set {
                this.menuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://toro.2ch.net/test/read.cgi/win/1330826421/sm4win8.xsd")]
    public partial class startmenuSettingIcon {
        
        private bool visibleField;
        
        public startmenuSettingIcon() {
            this.visibleField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
            }
        }
    }
}
