//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.261
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartMenuForWin8.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StartMenuForWin8.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   All Programs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringAllPrograms {
            get {
                return ResourceManager.GetString("StringAllPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Apply に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringApply {
            get {
                return ResourceManager.GetString("StringApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringBack {
            get {
                return ResourceManager.GetString("StringBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringCancel {
            get {
                return ResourceManager.GetString("StringCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   We coudn&apos;t access the following file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringCantAccessFile {
            get {
                return ResourceManager.GetString("StringCantAccessFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The command coudn&apos;t be executed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringCantExecuteCommand {
            get {
                return ResourceManager.GetString("StringCantExecuteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Customize... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringCustomize {
            get {
                return ResourceManager.GetString("StringCustomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To customize how links, icons, and menus look and behave in the start menu, click Customize. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringCustomizeStartmenu {
            get {
                return ResourceManager.GetString("StringCustomizeStartmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Following Exception are catched. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringExceptionCatched {
            get {
                return ResourceManager.GetString("StringExceptionCatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file couldn&apos;t be opened. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringFileCantOpen {
            get {
                return ResourceManager.GetString("StringFileCantOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (None) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringNoneInFolder {
            get {
                return ResourceManager.GetString("StringNoneInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringOK {
            get {
                return ResourceManager.GetString("StringOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Power button Action: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringPowerButtonAction {
            get {
                return ResourceManager.GetString("StringPowerButtonAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Privacy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringPrivacy {
            get {
                return ResourceManager.GetString("StringPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Property に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringPropertInMenu {
            get {
                return ResourceManager.GetString("StringPropertInMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Menu Properties に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringPropertTitle {
            get {
                return ResourceManager.GetString("StringPropertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recently opned items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringRecentItems {
            get {
                return ResourceManager.GetString("StringRecentItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recently opened programs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringRecentPrograms {
            get {
                return ResourceManager.GetString("StringRecentPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Menu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringStartMenuTab {
            get {
                return ResourceManager.GetString("StringStartMenuTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Store and display recently opened _programs in the startmenu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringStoreRecentProgram {
            get {
                return ResourceManager.GetString("StringStoreRecentProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringTarget {
            get {
                return ResourceManager.GetString("StringTarget", resourceCulture);
            }
        }
    }
}
